name: Test features

on:
  pull_request:
    types: [ opened, edited ]
    paths:
      - '**.rs'
      - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain: [stable, nightly]
        fixed: ["fixed8", "fixed16", "fixed32", "fixed64"]
        std: [",std", ""]
        derive: [",derive", ""]
        bincoded: [",bincoded", ""]
    steps:
    - uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust-toolchain }}
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --no-default-features --features=${{ matrix.fixed }}${{ matrix.std }}${{ matrix.derive }}${{ matrix.bincoded }}
